### ISSUE TITLE
About parameter count

### ISSUE THREAD

**Issue by polo5** [starhiking/HeatmapInHeatmap#3]
Hey, thanks for the interesting work!

I'm trying to reproduce the number of parameters/Flops you report in the paper. You report `22M params / 17.15Gflops` for the largest model (HIH head with 4-HG backbone) but calling torchinfo on this model in your code gives me `18.9M params / 16.99G Mult-adds`.

Any idea for that disparity (esp in model params)? Thanks!

**Comment by starhiking** [comment]
Thanks for your attention!

I have used two tools(```ptflops```, ```thop```)  to count the params and flops, their results are a little different due to their count operations. The ```ptflops``` tool reports  17.15Gflops and 22.68M, and ```thop``` is 17.091Gflops and 18.962M. I am not sure what tool or count way other methods take, so I take the more complex results as model information.

To understand clearly the distinction, the below code added in ```get_hourglass.py``` may help you.

    if __name__ == "__main__":
        from experiments.Data_WFLW.HIHC_64x8_hg_l2 import Config 
        config = Config()
        model = StackedHourGlass(config)
    
        input = torch.randn(1,3,256,256)
    
        from ptflops import get_model_complexity_info
        flops, params = get_model_complexity_info(model, (3, 256, 256), as_strings=True, print_per_layer_stat=True,custom_modules_hooks={Attention:attention_flops_counter_hook})
        print('Flops:  ' + flops)
        print('Params: ' + params)

        from thop import profile,clever_format
        flops, params = profile(model,inputs=(input, ), verbose=True,
                                custom_ops={Attention:count_attention})   
        flops, params = clever_format([flops, params], "%.3f")
        print("FLOPs: {} Params: {}".format(flops,params))

**Comment by polo5** [comment]
Awesome, that's very helpful. Thanks :)
